_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 105
            "3":
                - 13
                - 16
                - 55
            "4": 3.11.12
            "5": 0.20.1
            "6": 4.51.3
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
image_size:
    value: 256
lr:
    value: 0.0002
num_epoch:
    value: 200
z_dim:
    value: 512
