version: '3.8'

services:
  pgm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports:
      - "4001:4001"
    container_name: pgm
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}