paths:
  data: ./data
  train: ${paths.data}/train
  test: ${paths.data}/test
  results: ./results
  checkpoints: ./experiments/checkpoints


data:
  train_mel: ${paths.train}/mel
  train_other: ${paths.train}/other
  test_mel: ${paths.test}/mel
  test_other: ${paths.test}/other

wandb:
  project_name: pgm-projekcik


train:
  diffusion:
    batch_size: 1
    image_size: 256
    num_epoch: 50
    lr: 1e-4
    checkpoint_path: ${paths.checkpoints}/diffusion/
    final_model: ${paths.results}/models/diffusion/final_model.pth
    log: True
  gan:
    batch_size: 64
    image_size: 256
    num_epoch: 200
    lr: 2e-4
    z_dim: 256
    checkpoint_path: ${paths.checkpoints}/gan/
    final_model: ${paths.results}/models/gan/final_model.pth
    log: True
  vae:
    batch_size: 32
    image_size: 256
    num_epoch: 100
    latent_dim: 64
    lr: 1e-5
    beta: 1.0
    kl_anneal_epochs: 20
    use_perceptual_loss: False
    checkpoint_path: ${paths.checkpoints}/vae/
    final_model: ${paths.results}/models/vae/final_model.pth
    log: True
  cnn:
    batch_size: 64
    num_classes: 2
    image_size: 256
    num_epoch: 20
    lr: 1e-4
    checkpoint_path: ${paths.checkpoints}/cnn/
    log: True
    final_model:
      base: ${paths.results}/models/cnn/final_model_base.pth
      gan: ${paths.results}/models/cnn/final_model_gan.pth
      diffusion: ${paths.results}/models/cnn/final_model_diffusion.pth
      vae: ${paths.results}/models/cnn/final_model_vae.pth

generate:
  num_samples: 5
  diffusion:
    model_checkpoint: TRZEBA PODAĆ
    result_path: ${paths.results}/diffusion/samples
  vae:
    model_checkpoint: TRZEBA PODAĆ
    result_path: ${paths.results}/vae/samples
  gan:
    model_checkpoint: TRZEBA PODAĆ
    result_path: ${paths.results}/gan/samples